var questions = [
		{question: "Jaki sposób komunikacji z ludźmi jest dla Ciebie bardziej typowy?", 
		choices: ["Nie dostrzegam dystansu między ludźmi zbyt dobrze, preferuje zachowywać się jednakowo między ludzmi.", 
		"Wyczuwam nastawienie ludzi do mnie, wiem na jakim dystansie się z nimi komunikować."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:0,LSI:0,EIE:1,IEI:1,LIE:0,ILI:0,SEE:1,ESI:1,LSE:0,SLI:0,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Jaki rodzaj odpoczynku preferujesz?", 
		choices: ["Aktywny: sport, spacery, chodzenie na zakupy itd.", 
		"Pasywny: czytanie, oglądanie filmów, myślenie lub po prostu marzenie."],
		score: {ESE:0,LSE:0,SLE:0,LSI:0,SEE:0,ESI:0,ILE:1,SEI:1,IEI:1,ILI:1,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Do czego przywiązujesz wagę jeśli jesteś pierwszy raz w nieznanym mieście lub kraju?", 
		choices: ["Historii, niespotykanych i unikalnych osobliwości, perspektyw.", 
		"Piękna budynków, rodzaju ubrań jakie ludzie noszą, jakie potrawy jedzą."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:1,LSI:1,EIE:0,IEI:0,LIE:0,ILI:0,SEE:1,ESI:1,LSE:1,SLI:1,IEE:0,EII:0}, checked: -1, skipped: false},
		{question: "Jak zmienia się Twój nastrój?", 
		choices: ["Często z niezrozumiałych/nieświadomwych powodów.", 
		"Zawsze wiem co jest przyczyną zmiany mojego nastroju."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:0,LSI:0,EIE:1,IEI:1,LIE:0,ILI:0,SEE:1,ESI:1,LSE:0,SLI:0,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Co jest bardziej typowe dla Ciebie?", 
		choices: ["Spięcie mięśni, ciężko jest mi w pełni się zrelaksować.", 
		"Mięśnie są zrelaksowane, ciężko jest mi utrzymać ciągłe napięcie mięśni."],
		score: {ILE:1,LII:1,ESE:1,SEI:1,SLE:0,LSI:0,EIE:0,IEI:0,LIE:0,ILI:0,SEE:0,ESI:0,LSE:1,SLI:1,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Co myślisz, że jest charakterystyczne dla Ciebie?", 
		choices: ["Jestem otwartą osobą, lubię pokazywać jak pracuję.", 
		"Jestem powściągliwy, unikam rywalizacji."],
		score: {ESE:0,EIE:0,SLE:0,LSI:0,LIE:0,SEE:0,ESI:0,LSE:0,ILE:1,LII:1,SEI:1,IEI:1,ILI:1,SLI:1,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Do czego przykładasz większą uwagę w nowym mieście lub kraju?", 
		choices: ["Cen, zasad, procedur.", 
		"Nastroju ludzi, sposobu ich komunikacji, emocji jakie czują."],
		score: {ILE:0,LII:0,SLE:0,LSI:0,LIE:0,ILI:0,LSE:0,SLI:0,ESE:1,SEI:1,EIE:1,IEI:1,SEE:1,ESI:1,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Co jest bardziej typowe dla Ciebie?", 
		choices: ["Zainteresowanie nowościami, jesteś jednym z pierwszych który jest zainteresowany nowym podejściem.", 
		"Preferujesz zwykłe i sprawdzone rzeczy, nie spieszysz się do sprawdzenia nowości."],
		score: {ILE:0,LII:0,IEE:0,EII:0,SLE:1,LSI:1,SEE:1,ESI:1}, checked: -1, skipped: false},
		{question: "Twoje myślenie częściej jest", 
		choices: ["Konkretne, ukierunkowane, efektywne.", 
		"Abstrakcyjne."],
		score: {ESE:0,SEI:0,SLE:0,LSI:0,SEE:0,ESI:0,LSE:0,SLI:0,ILE:1,LII:1,EIE:1,IEI:1,LIE:1,ILI:1,IEE:1,EII:1}, checked: -1, skipped: false},
		{question: "Co jest bardziej typowe dla Ciebie?", 
		choices: ["Pozyskuje więcej informacji ze słów osoby której słucham.", 
		"Pozyskuje więcej informacji ze sposobu, ekspresji i intonacji osoby której słucham."],
		score: {ESE:0,SEI:0,EIE:0,IEI:0,SEE:0,ESI:0,IEE:0,EII:0,ILE:1,LII:1,SLE:1,LSI:1,LIE:1,ILI:1,LSE:1,SLI:1}, checked: -1, skipped: false},
		{question: "Czego częściej Ci brakuje?", 
		choices: ["Informacji.", 
		"Energii."],
		score: {ESE:0, SEI:0, EIE:0, IEI:0, SEE:0, ESI:0, IEE:0, EII:0, ILE:1, LII:1, SLE:1, LSI:1}, checked: -1, skipped: false},
		{question: "Jak zwykle sprzątasz pokój?", 
		choices: ["Staram się sprzątać według ustalonej kolejności.", 
		"Zmieniam kolejność wykonywanych czynności. Nie zależy mi aby sprzątać według ustalonej kolejności "],
		score: {LII:0, ESE:0, LSI:0, EIE:0, LIE:0,ESI:0,LSE:0,EII:0,ILE:1,SEI:1,SLE: 1,IEI:1,ILI:1,SEE:1,SLI:1,IEE:1}, checked: -1, skipped: false},
		{question: "Co bardziej pasuje do Ciebie?", 
		choices: ["Starać się zbyt bardzo, dążyć do perfekcjonizmu.", 
		"Hamować się, nie potrzebuje być perfekcyjny."],
		score: {ILE:1,LII:0,ESE:0,SEI:1,SLE:1,LSI:1,EIE:1,IEI:1,LIE:0,ILI:1,SEE:1,ESI:0,LSE:0,SLI:1,IEE:1,EII:0},checked: -1, skipped: false},
		{question: "Z czym sobie lepiej radzisz?", 
		choices: ["Faktami, danymi, wydarzeniami.", 
		"Relacjami międzyludzkimi i sympatiamii."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:0,LSI:0,EIE:1,IEI:1,LIE:0,ILI:0,SEE:1,ESI:1,LSE:0,SLI:0,IEE:1,EII:1},checked: -1, skipped: false},
		{question: "Co robisz lepiej?", 
		choices: ["Lepiej idzie Ci z wymyślaniem planów i teorii.", 
		"Lepiej idzie Ci z realizowaniem planów i teorii."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:1,LSI:1,EIE:0,IEI:0,LIE:0,ILI:0,SEE:1,ESI:1,LSE:1,SLI:1,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystycznego dla Ciebie?", 
		choices: ["Szybko się namyślasz w zwykłych sytuacjach, gubisz się w niezwykłych.", 
		"Wątpisz w zwykłych sytuacjach, ale w niezwykłych szybko podejmujesz decyzję."],
		score: {ILE:1,LII:0,ESE:0,SEI:1,SLE:1,LSI:0,EIE:0,IEI:1,LIE:0,ILI:1,SEE:1,ESI:0,LSE:0,SLI:1,IEE:1,EII:0},checked: -1, skipped: false},
		{question: "Które wartości duchowe pasują do Ciebie bardziej?",
		choices: ["Umysł, entuzjazm i perspektywy.", 
		"Nowe możliwości i teorie, inspiracje, zabawy i komfort",
		"Przytulność i dobrobyt w domu, pokój na całym świecie, stabilność społeczna"],
		score: {ILE:1,LII:1,ESE:2,SEI:2,SLE:0,LSI:0,EIE:0,IEI:0,LIE:0,ILI:0,SEE:0,ESI:0,LSE:2,SLI:2,IEE:2,EII:2},checked: -1, skipped: false},
		{question: "Które z elementów poniżej najbardziej nie lubisz?",
		choices: ["Ram czasowych, ograniczeń moralnych i etycznych, granice kodeksów i przepisów.", 
		"Głośne hasła, ograniczenia działalności gospodarczej.",
		"Dyskomfort, ingerencja w wewnętrzne życie człowieka, idea 'odległej świetlanej przyszłości",
		"Mieszczaństwo, słabość, niepewność, nieodpowiedzialność."],
		score: {ILE:0,LII:0,ESE:2,SEI:2,SLE:0,LSI:0,EIE:2,IEI:2,LIE:1,ILI:1,SEE:3,ESI:3,LSE:1,SLI:2,IEE:3,EII:3},checked: -1, skipped: false},
		{question: "Które z marzeń poniżej najbardziej pragniesz?",
		choices: ["Być wielkim naukowcem, wymyślaniem niezwykłych rzeczy, komunikować się z osobami o podobnych poglądach.", 
		"Odnieść sukces jako przedsiębiorca, prowadzić wielką korporację, wprowadzenie do praktyki nowych technologii.",
		"Być liderem politycznym i duchowym, być szefem silnej partii lub ruchu.",
		"Mieć wszystkiego pod dostatkiem przez reszte swojego życia, żyć z rodziną w wielkim domu blisko natury."],
		score: {ILE:0,LII:0,ESE:3,SEI:3,/*SLE:0,LSI:1,EIE:1,IEI:0,*/LIE:1,ILI:1,SEE:2,ESI:2,LSE:1,SLI:3,IEE:3,EII:3},checked: -1, skipped: false},
		{question: "W jakiego rodzaju pracy myślisz, że odniesiesz największy sukces?",
		choices: ["Nauka, obszar o wysokiej technologii.", 
		"Komunikacja z ludźmi, rozwiązywanie codziennych problemów życiowych człowieka.",
		"Przemysł, działalność w zakresie zarządzania.",
		"Praca twórcza w dziedzinie humanitarnej."],
		score: {ILE:0,LII:0,ESE:1,SEI:1,SLE:2,LSI:2,EIE:3,IEI:3,LIE:0,ILI:0,SEE:1,ESI:1,LSE:2,SLI:2,IEE:3,EII:3},checked: -1, skipped: false},
		{question: "Które z elementów jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Prostolinijność, pośpiech, dawanie wszystkiego co mam dla sprawy.", 
		"Elastyczność zachowania, spokojne zmiany, często zmieniasz sposób pracy.",
		"Trwałe opanowanie i kontrola emocji.",
		"Ucieczka od konfliktów, wrażliwość na nawet małe zmiany sytuacji, na zewnątrz spokojny."],
		score: {ILE:1,LII:1,ESE:0,SEI:3,SLE:2,LSI:2,EIE:0,IEI:3,LIE:0,ILI:2,SEE:0,ESI:2,LSE:0,SLI:2,IEE:1,EII:3},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Stanowczość, systematyczność, realizm, pragmatyzm i praktyczność.", 
		"Komunikatywny humor, nieformalne relacje, interakcje grupy.",
		"Szukanie ideałów i emocjonalnej harmonii, umiejętność dzielenia smutków drugiej osoby.",
		"Zainteresowanie do niezbadanego i niezwykłego, ciekawość, jesteś chętny do eksperymentowania."],
		score: {ILE:3,LII:3,ESE:1,SEI:1,SLE:0,LSI:0,EIE:2,IEI:2,LIE:1,ILI:1,SEE:1,ESI:1,LSE:0,SLI:0,IEE:2,EII:2},checked: -1, skipped: false},
		{question: "Jak komunikujesz się z płcią przeciwną na samym początku znajomości?",
		choices: ["Według zwykłego standardowego schematu, nie ma zbyt dużej inicjatywy z mojej strony.", 
		"Mam aktywną postawę w komunikacji, przejmuję inicjatywe, ale nie w dziedzinie uczuć.",
		"Komunikacja to emocjonalna wymiana, często podejmuję inicjatywe.",
		"Daję sygnały, że lubię daną osobę, staram się wspierać inicjatywe."],
		score: {ILE:0,LII:0,ESE:2,SEI:2,SLE:1,LSI:1,EIE:3,IEI:3,LIE:0,ILI:0,SEE:2,ESI:2,LSE:1,SLI:1,IEE:3,EII:3},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystycznego dla Ciebie?",
		choices: ["Jesteś zwolennikiem równości praw, rewolucjonisty.", 
		"Jesteś zwolennikiem jasnego przypisywania ról, szacunku dla ludzi wyżej w hierarchii, konserwatywny."],
		score: {ILE:0,LII:0,ESE:0,SEI:0,SLE:0,LSI:0,EIE:0,IEI:0,LIE:1,ILI:1,SEE:1,ESI:1,LSE:1,SLI:1,IEE:1,EII:1},checked: -1, skipped: false},
		{question: "Czy Twój nastrój zmienia się pod wpływem ludzi którzy Cie otaczają?",
		choices: ["Zywkle mój nastrój zmienia się pod wpływem innych ludzi.", 
		"Zywkle mój nastrój nie zmienia się pod wpływem innych ludzi."],
		score: {ILE:1,LII:1,ESE:0,SEI:0,SLE:1,LSI:1,EIE:0,IEI:0,LIE:1,ILI:1,SEE:0,ESI:0,LSE:1,SLI:1,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Jaki masz stosunek co do ustawienia rzeczy w Twoim domu?",
		choices: ["Próbuje dopasować stałe miejsce dla każdej rzeczy.", 
		"Porządek nie jest dla mnie niezbędny."],
		score: {ILE:1,LII:1,ESE:0,SEI:0,SLE:0,LSI:0,EIE:1,IEI:1,LIE:1,ILI:1,SEE:0,ESI:0,LSE:1,SLI:1,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Jaki masz stosunek do konfliktów z Twoimi przyjaciółmi, co jest dla Ciebie bardziej charakterystyne?",
		choices: ["Na spór patrzę przez pryzmat uczuć.", 
		"Spór analizuję w logiczny sposób."],
		score: {ILE:1,LII:1,ESE:0,SEI:0,SLE:1,LSI:1,EIE:0,IEI:0,LIE:1,ILI:1,SEE:0,ESI:0,LSE:1,SLI:1,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Żyjesz \"tu i teraz\".", 
		"Żyjesz w przeszłości lub w przyszłości."],
		score: {ILE:1,LII:1,ESE:0,SEI:0,SLE:0,LSI:0,EIE:1,IEI:1,LIE:1,ILI:1,SEE:0,ESI:0,LSE:0,SLI:0,IEE:1,EII:1},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie kiedy jesteś na imprezie?",
		choices: ["Szybko się męczysz, preferujesz wcześniej skończyć i iść do domu.", 
		"Możesz bawić się do rana i nie czuć zmęczenia."],
		score: {ILE:1,LII:0,ESE:1,SEI:0,SLE:1,LSI:0,EIE:1,IEI:0,LIE:1,ILI:0,SEE:1,ESI:1,LSE:1,SLI:0,IEE:1,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Z początku dostrzegam pozytywy, coś co \"jest\" np. szklanka do połowy pełna.", 
		"Z początku dostrzegam negatywy, braki czegoś np. szklanka do połowy pusta."],
		score: {ILE:0,LII:1,ESE:0,SEI:1,SLE:1,LSI:0,EIE:1,IEI:0,LIE:0,ILI:1,SEE:0,ESI:1,LSE:1,SLI:0,IEE:1,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Dostrzegam proces w pracy, praca absorbuje mnie w całości, nie lubię zmian pomiędzy wykonywanymi pracami.",
		"Często wykonuję wiele rzeczy na raz, łatwo zmieniam się pomiędzy wykonywanymi czynnościami."],
		score: {ILE:1,LII:1,ESE:0,SEI:0,SLE:0,LSI:0,EIE:1,IEI:1,LIE:1,ILI:1,SEE:0,ESI:0,LSE:1,SLI:1,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Które zdanie z poniższych jest według Ciebie bardziej poprawne?",
		choices: ["Nie ma unikalnie poprawnych odpowiedzi, wszystko jest subiektywne.", 
		"Istnieje wiele sytuacji w których istnieje obiektywnie prawidłowa decyzja."],
		score: {ILE:0,LII:0,ESE:0,SEI:0,SLE:1,LSI:1,EIE:1,IEI:1,LIE:1,ILI:1,SEE:1,ESI:1,LSE:0,SLI:0,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Twój normalny stan to bezczynność, mobilizujesz się w momencie rozpoczęcia pracy.", 
		"Jesteś zawsze w stanie mobilizacji, czasami trudno jest Ci się zre po skończonej pracy."],
		score: {ILE:0,LII:0,ESE:0,SEI:0,SLE:1,LSI:1,EIE:1,IEI:1,LIE:1,ILI:1,SEE:1,ESI:1,LSE:0,SLI:0,IEE:0,EII:0},checked: -1, skipped: false},
		{question: "Co jest bardziej charakterystyczne dla Ciebie?",
		choices: ["Zwykle stawiam sobie cele, które mogę osiągnąć w najbliższej przyszłości.", 
		"Zwykle ustalam wielkie cele, które mogę osiągnąć w dalekiej przyszłości."],
		score: {ILE:0,LII:1,ESE:1,SEI:0,SLE:1,LSI:0,EIE:0,IEI:1,LIE:0,ILI:1,SEE:1,ESI:0,LSE:1,SLI:0,IEE:0,EII:1},checked: -1, skipped: false},
		{question: "W jaki sposób zwykle działasz w zupełnie nowej sytaucji?",
		choices: ["Polegam na całym moim doświadczeniu, nawet jeśli nie jest ono do końca związane z tą konkretną sytuacją.", 
		"Używam informacji które są mi dane tylko w tej konkretnej sytuacji, nowe zadania są unikalne."],
		score: {ILE:1,LII:0,ESE:0,SEI:1,SLE:1,LSI:0,EIE:0,IEI:1,LIE:0,ILI:1,SEE:1,ESI:0,LSE:0,SLI:1,IEE:1,EII:0},checked: -1, skipped: false},
		{question: "Które z wymienionych są Twoją mocną stroną?",
		choices: ["Zmysłowość, zdolność do empatii, zdolność do udzielania porad w trudnych sytuacjach moralnych.", 
		"Towarzyskość, aktywność społeczna, zdolność, aby zapewnić komfort dla przyjaciół i rodziny.",
		"Wiedza, pomysłowość, zdolność do znalezienia odpowiedzi na wiele pytań.",
		"Niezawodność, funkcjonalność, zdolność do pracy przy wielu codziennych problemach."],
		score: {ILE:2,LII:2,ESE:1,SEI:1,SLE:3,LSI:3,EIE:0,IEI:0,LIE:2,ILI:2,SEE:1,ESI:1,LSE:3,SLI:3,IEE:0,EII:0},checked: -1, skipped: false},
	];
	